baseURL: "http://eazyreal.github.io/"
languageCode: "en-us"
title: "Maxwill's Site"
theme: "PaperMod"

# SEO...

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

## Top Nav
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: CV
      name: CV
      url: /cv
      weight: 10
    - identifier: Search
      name: Search
      url: /search
      weight: 99

## Below is for PaperMod theme

params:
  # this is passed \themes\PaperMod\layouts\partials\head.html
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon.ico"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "favicon.ico"
    safari_pinned_tab: "favicon.ico"
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Maxwill's Site
  description: Maxwill's Site
  keywords: [Blog, Portfolio]
  author: ["Maxwill"]
  images:
    [
      "https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png",
    ]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Maxwill's Site"
    icon: "favicon.ico"
    iconHeight: 20

  # profile-mode
  profileMode:
    enabled: true
    title: "Maxwill's Site"
    subtitle: Make things as simple as possible, but not simpler
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: "<title of image as alt>"
    buttons:
      - name: CV
        url: cv
      - name: Tags
        url: tags
      - name: Search
        url: search
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to Maxwill's Blog

  # choose mode above

  # Socials
  socialIcons:
    - name: twitter
      url: "https://twitter.com/tensorfi"
    - name: github
      url: "https://github.com/eazyreal"

  analytics:
    google:
      SiteVerificationTag: "Maxwill"
    bing:
      SiteVerificationTag: "Maxwill"
    yandex:
      SiteVerificationTag: "Maxwill"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/EazyReal/eazyreal.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     # anchorLineNos: true
#     codeFences: true
#     guessSyntax: true
#     lineNos: true
#     style: monokai
