# Project information
site_name: Maxwill's site
site_description: Maxwill's personal website
site_author: Maxwill
site_url: https://maxwill.one/

# Repository
repo_name: EazyReal/eazyreal.github.io
repo_url: https://github.com/EazyReal/eazyreal.github.io
edit_uri: https://github.com/EazyReal/eazyreal.github.io/tree/main/docs/

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode=
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.follow
    - header.autohide
  font:
    text: "Roboto"
    code: "Roboto Mono"
  icon:
    logo: "img/infinity.svg"
    repo: fontawesome/brands/git-alt
  logo: "img/infinity.svg"
  favicon: "img/favicon.ico"

extra:
  #social links at btm
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/EazyReal"
    - icon: fontawesome/brands/facebook
      link: "https://www.facebook.com/maxwill.lin"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/maxwilllin/"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/tensorfi"

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - attr_list
  - admonition
  - mdx_math: # python-markdown-math
      enable_dollar_delimiter: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - git-revision-date
  - tags:
      tags_file: tags.md
  # - macros:

# for math
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
