# Project information
site_name: Maxwill's site
# site_description: 'Maxwill's personal website'
# site_author: 'Maxwill - Yan-Tong Lin'
# site_url: 'https://eazyreal.github.io/'

# Repository
# repo_name: 'EazyReal/eazyreal.github.io'
# repo_url: 'https://github.com/EazyReal/eazyreal.github.io'

# Navigation
nav:
    - 'Home': 'index.md'
    - 'CV': 'cv.md'
    - 'About': 'about.md'
    - 'NLP': 
      - 'Standford 224n' : 'NLP\stanford224n-home.md'
      - 'Paper List 2020 Summer' : 'NLP\paperlist2020summer.md'
    - 'Quantum':
      - 'Quantum Compuation and Quantum Information' : 'Quantum\QIC.md'
    - 'Math':
      - 'Linear Algebra II' : 'Math\LAII.md'
      - 'Introduction to Real Analysis II' : 'Math\IntroRAII.md'

# Theme
theme:
    name: 'material'
    custom_dir: 'overrides'
    palette:
        scheme: 'default'
        primary: 'teal'
        accent: 'indigo'
    features:
        - 'tabs'
        #- 'instant'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    icon:
        logo: 'img/infinity.svg'
        repo: fontawesome/brands/git-alt
    # at upper left
    logo: 'img/infinity.svg'
    # at browser's tab
    favicon: 'img/favicon.ico'

extra:
#social links at btm
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/EazyReal'
    - icon: fontawesome/brands/facebook
      link: 'https://www.facebook.com/profile.php?id=100016734543516'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/yan-tong-lin-ba4a72194/'

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true