# this deploy github action is from https://squidfunk.github.io/mkdocs-material/publishing-your-site/
# Maxwill changed run: pip install mkdocs-material to pip install -r requirements.txt
name: ci
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install
      - run: uv sync --locked
      - run: uv run mkdocs gh-deploy --force
